<!DOCTYPE sql-queries [
<!ELEMENT sql-queries (sql-query)*>
<!ELEMENT sql-query (#PCDATA)>
<!ATTLIST sql-query id CDATA #REQUIRED>
]>
<sql-queries>
<!-- Master Data Queries -->
<sql-query id="getInputSources">
     <![CDATA[SELECT * FROM cms_route_of_enquiry;]]>
</sql-query>
<sql-query id="getEnquirers">
     <![CDATA[SELECT * FROM cms_enquirers;]]>
</sql-query>
<sql-query id="getNatureofEnquiries">
     <![CDATA[SELECT * FROM cms_nature_of_enquiry;;]]>
</sql-query>  

<sql-query id="getCaseInfo">
     <![CDATA[SELECT
                    c.*,
                    cc.country_name as countryName,
                    cc.country_code as countryCode,
                    cre.name as routeOfEnquiryId,
                    cre.type as routeOfEnquiryType,
                    cne.name as natureOfEnquiryId,
                    DATEDIFF(CURDATE(), DATE_FORMAT(c.receievedDate, '%Y-%m-%d')) as dueDays,
                    csrd.reporterSalutation, csrd.reporterName, csrd.reporterEmail, csrd.reporterFax, csrd.reporterPhone, csrd.reporterState, csrd.reporterCountry, csrd.reporterStreet, csrd.reporterPostalCode, csrd.reporterCity, csrd.reporterAddress, csrd.reporterContactMethod, csrd.regulatoryAuthorityName, csrd.otherReportedBy,
                    (CASE WHEN csrd.isPrimaryReporter = 1 THEN 'Yes' WHEN csrd.isPrimaryReporter = 0 THEN 'No' WHEN csrd.isPrimaryReporter is null THEN '' END) as isPrimaryReporter,
                    (CASE WHEN c.isCaseValid = 1 THEN 'Accepted' WHEN c.isCaseValid = 0 THEN 'Rejected' WHEN c.isCaseValid is null THEN '' END) as isCaseValid,
                    (CASE WHEN c.isReportisSamePatient = 1 THEN 'Yes' WHEN c.isReportisSamePatient = 0 THEN 'No' WHEN c.isReportisSamePatient is null THEN '' END) as isReportisSamePatient,
                    (CASE WHEN c.isFollowupRequired = 1 THEN 'Yes' WHEN c.isFollowupRequired = 0 THEN 'No' WHEN c.isFollowupRequired is null THEN '' END) as isFollowupRequired,
                    (CASE WHEN c.isContractTreatingPhysician = 1 THEN 'Yes' WHEN c.isContractTreatingPhysician = 0 THEN 'No' WHEN c.isContractTreatingPhysician is null THEN '' END) as isContractTreatingPhysician,
                    (CASE WHEN c.isFollowupDone = 1 THEN 'Yes' WHEN c.isFollowupDone = 0 THEN 'No' WHEN c.isFollowupDone is null THEN '' END) as isFollowupDone,
                    (CASE WHEN c.patientGender = 'M' THEN 'Male' WHEN c.patientGender = 'F' THEN 'Female' WHEN c.patientGender is null THEN '' END) as patientGender,
                    (CASE WHEN c.isPatientisbaby = 1 THEN 'Yes' WHEN c.isPatientisbaby = 0 THEN 'No' WHEN c.isPatientisbaby is null THEN '' END) as isPatientisbaby,
                    (CASE WHEN c.isoutcomefatal = 1 THEN 'Yes' WHEN c.isoutcomefatal = 0 THEN 'No' WHEN c.isoutcomefatal is null THEN '' END) as isoutcomefatal,
                    (CASE WHEN c.studyInfoAvailable = 1 THEN 'Yes' WHEN c.studyInfoAvailable = 0 THEN 'No' WHEN c.studyInfoAvailable is null THEN '' END) as studyInfoAvailable,
                    (CASE WHEN csrd.ishealthcareprofessional = 1 THEN 'Yes' WHEN csrd.ishealthcareprofessional = 0 THEN 'No' WHEN csrd.ishealthcareprofessional is null THEN '' END) as ishealthcareprofessional,
                    (CASE WHEN csrd.isReporterDrugRegulatorAuthority = 1 THEN 'Yes' WHEN csrd.isReporterDrugRegulatorAuthority = 0 THEN 'No' WHEN isReporterDrugRegulatorAuthority is null THEN '' END) as isReporterDrugRegulatorAuthority,
                    (
                         CASE
                         WHEN
                              c.patientAgegroup = '1'
                         THEN
                              'Neonate'
                         WHEN
                              c.patientAgegroup = '2'
                         THEN
                              'Infant'
                         WHEN
                              c.patientAgegroup = '3'
                         THEN
                              'Child'
                         WHEN
                              c.patientAgegroup = '4'
                         THEN
                              'Adolescent'
                         WHEN
                              c.patientAgegroup = '5'
                         THEN
                              'Adult'
                         WHEN
                              c.patientAgegroup = '6'
                         THEN
                              'Elderly'
                         ELSE
                              ''
                         END
                    )
                    AS patientAgegroup,
                    (
                         CASE
                         WHEN
                              c.caseComplexity = 'P1'
                         THEN
                              'Priority 1'
                         WHEN
                              c.caseComplexity = 'P2'
                         THEN
                              'Priority 2'
                         WHEN
                              c.caseComplexity = 'P3'
                         THEN
                              'Priority 3'
                         WHEN
                              c.caseComplexity = '4'
                         THEN
                              'Adolescent'
                         WHEN
                              c.caseComplexity = '5'
                         THEN
                              'Adult'
                         ELSE
                              ''
                         END
                    )
                    AS caseComplexity, 
                    (select group_concat(name) from cms_case_classifications ccc where find_in_set(ccc.id, c.caseClassification)) as caseClassification,
                    (select group_concat(productName) from cms_argus_product_dictionary ccp where find_in_set(ccp.id, c.productId)) as productId,
                    cc.country_name as patientCountry, cc1.country_name as physicianCountry, cc2.country_name as reporterCountry, ce.name as reportedBy, cre1.name as reporterContactMethod
                    FROM
                    cms_cases c
                    left outer join
                         cms_countries cc
                         on cc.id = c.patientCountry
                    left outer join
                         cms_countries cc1
                         on cc1.id = c.physicianCountry
                    left outer join
                         cms_route_of_enquiry cre
                         on cre.id = c.routeOfEnquiryId
                    left outer join
                         cms_nature_of_enquiry cne
                         on cne.id = c.natureOfEnquiryId
                    left outer join
                         cms_case_reporter_details csrd
                         on csrd.caseId = c.id and csrd.isPrimaryReporter = 1
                    left outer join
                         cms_enquirers ce
                         on ce.id = csrd.reportedBy
                    left outer join
                         cms_countries cc2
                         on cc2.id = csrd.reporterCountry
                    left outer join
                         cms_route_of_enquiry cre1
                         on cre1.id = csrd.reporterContactMethod
                         and cre1.type = 'ContactMethod' WHERE ]]>
</sql-query>
<sql-query id="getCaseCount">
     <![CDATA[select
          COUNT(c.id) as count 
               from
          cms_cases c 
          WHERE ]]>
</sql-query>
<sql-query id="getCountriesData">
     <![CDATA[SELECT * FROM cms_argus_countries;]]>
</sql-query>
<sql-query id="getSearchProductData">
     <![CDATA[SELECT *,CONCAT_WS(" ",concUnitId, concentration) as strengths from cms_argus_product_dictionary WHERE active = 1  ]]>
</sql-query>
<sql-query id="getSearchProductDataCount">
     <![CDATA[SELECT COUNT(id) as count from cms_argus_product_dictionary WHERE active = 1 ]]>
</sql-query>
<sql-query id="saveCaseProductData">
     <![CDATA[INSERT INTO cms_case_products(`productId`, `caseId`, `productName`, `manufacturedBy`, `strengths`, `size`, `ncdNumber`, `lotNumber`,  `numberOfBottle`, `exipiryDate`, `country`, `maNumber`, `activeIngredient`, `type`, `createdBy`, `createdDate`,  `active`, `caseClassification`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);]]>
</sql-query>
<sql-query id="getCaseProductData">
     <![CDATA[SELECT * FROM cms_case_products WHERE caseId = ? and productId in (?);]]>
</sql-query>
<sql-query id="getCaseProductIds">
     <![CDATA[SELECT * FROM cms_case_products WHERE caseId = ? and productId = ?;]]>
</sql-query>
<sql-query id="caseProductExistancyById">
     <![CDATA[SELECT * FROM cms_case_products WHERE productId = ? AND caseId = ?;]]>
</sql-query>
<sql-query id="getCaseProductIdsArray">
     <![CDATA[SELECT productId FROM cms_case_products WHERE caseId = ?;]]>
</sql-query>
<sql-query id="getProductsByCaseId">
     <![CDATA[SELECT *, productId as id, 1 as selected From cms_case_products WHERE active = 1 and caseId = ?;]]>
</sql-query>
<sql-query id="getCaseProductExistency">
     <![CDATA[SELECT id From cms_case_products WHERE active = 1 and productId = ? and caseId = ?;]]>
</sql-query>
<sql-query id="getProductsByCountryId">
     <![CDATA[SELECT *, CONCAT_WS(" ",concUnitId, concentration) as strengths, 0 as selected
          FROM cms_argus_product_dictionary WHERE FIND_IN_SET(id, ?) and country = ?;]]>
</sql-query>
<sql-query id="deleteCaseProductById">
     <![CDATA[DELETE FROM cms_case_products WHERE productId = ? and caseId = ?;]]>
</sql-query>
<sql-query id="updateCaseProductDataById">
     <![CDATA[UPDATE cms_case_products SET `caseClassification` = ?, `modifiedBy` = ?, `modifiedDate` = ?  where productId = ? and caseId = ?;]]>
</sql-query>
<sql-query id="updateCaseProductData">
     <![CDATA[UPDATE cms_case_products SET `productName` = ?, `manufacturedBy` = ?, `strengths` = ?, `size` = ?, `ncdNumber` = ?, `lotNumber` = ?, `numberOfBottle` = ?, `exipiryDate` = ?, `country` = ?, `maNumber` = ?, `activeIngredient` = ?, `type` = ?, `modifiedBy` = ?, `modifiedDate` = ?, `caseClassification` = ?  where `productId` = ? and `caseId` = ?;]]>
</sql-query>
<sql-query id="deleteProducts">
      <![CDATA[UPDATE cms_argus_product_dictionary SET `active` = 0 WHERE id=?;]]>
</sql-query>

<sql-query id="getClassifications">
     <![CDATA[SELECT * FROM cms_case_classifications;]]>
</sql-query>
<sql-query id="getClassificationsParam">
     <![CDATA[SELECT id, name FROM cms_case_classifications;]]>
</sql-query>
<sql-query id="getContactMethods">
     <![CDATA[SELECT * FROM cms_route_of_enquiry where type = ?;]]>
</sql-query>
<sql-query id="getCountries">
     <![CDATA[SELECT * FROM cms_countries;]]>
</sql-query>
<sql-query id="getRegulatoryAuthorities">
     <![CDATA[SELECT * FROM cms_regulatory_authorities;]]>
</sql-query>
<!-- END -->

<!-- Auth Queries -->
<sql-query id="getLogin">
     <![CDATA[SELECT cu.*, cr.name as roleName, cr.masterRoleId, cs.sendCaseStatus, cs.recieveCaseStatus FROM cms_user cu
               left outer join cms_role cr on cr.id = cu.user_role_id
               left outer join cms_case_status cs on cs.id = cr.caseStatusId
               where userId = ? and password = ?;]]>
</sql-query>
<sql-query id="updateInvalidAttempts"> 
     <![CDATA[UPDATE cms_user SET loginAttempts = ?, active = ? where id = ?;]]>
</sql-query>
<sql-query id="updateRequestForPasswordCount"> 
     <![CDATA[UPDATE cms_user SET requestForPasswordCount = ? where userId = ?;]]>
</sql-query>
<sql-query id="getRolePermissions"> 
     <![CDATA[SELECT  * FROM cms_role_permissions where role_id = ?;]]>
</sql-query>
<sql-query id="getPermissionNames">
     <![CDATA[SELECT permission from cms_permissions where id in (?);]]>
</sql-query>
<sql-query id="getModulePermissions">
     <![CDATA[SELECT cp.permission from cms_permissions cp 
left join cms_role_permissions crp ON FIND_IN_SET(cp.id, crp.permission_ids) 
where crp.role_id = ? and cp.moduleId = ?;]]>
</sql-query>
 <sql-query id="activateDeactivateRole">
     <![CDATA[update cms_role SET active = ? where id = ?;]]>
    </sql-query> 
<sql-query id="getUsersBasedOnRole">
     <![CDATA[SELECT id, username,active FROM cms_user where user_role_id = ?;]]>
</sql-query>
<sql-query id="getUserRoleId">
     <![CDATA[SELECT id FROM cms_role where name = ?;]]>
</sql-query>
<sql-query id="getUserRoles">
     <![CDATA[SELECT id as roleid, name as rolename FROM cms_role WHERE isMasterRole is null;]]>
</sql-query>
<sql-query id="getModulesPermission">
     <![CDATA[SELECT cm.id, cm.moduleName, cr.isMasterRole from cms_modules cm  
          inner join cms_role_modules crm on FIND_IN_SET(cm.id, crm.moduleIds)
          inner join cms_role cr on cr.masterRoleId = crm.id where cr.id = ? order by cm.id;]]>
</sql-query>
<sql-query id="getModulePermissionsByRole">
     <![CDATA[SELECT * FROM cms_role_permissions crp
               left join cms_permissions cp on find_in_set(cp.id, crp.permission_ids) 
               left join cms_modules cm on cm.id = cp.moduleId
          where cp.moduleId = ? and crp.role_id = ? group by crp.role_id;]]>
</sql-query>
<sql-query id="getPermissionsList">
     <![CDATA[SELECT cp.id as permissionId, cp.permissions_display_name, cp.permission, cm.moduleName, cm.id as moduleId
               from cms_permissions cp left join cms_modules cm on FIND_IN_SET(cm.id,cp.moduleId)]]>
</sql-query>
<sql-query id="getmasterroles">
     <![CDATA[SELECT * FROM cms_role where isMasterRole = ?;]]>   
</sql-query>

<!-- END -->

<!-- Case Queries-->
<sql-query id="postEnquiryDetails">
     <![CDATA[INSERT INTO cms_cases(`registrationId`, `version`,`isCaseValid`, `reasonForRejection`,`reasonForAcceptance`,`reportedDate`, `routeOfEnquiryId`, `caseSourceDocumentIds`,
      `receievedDate`, `caseSubject`, `caseDescription`, `isFollowupRequired`, `isFollowupDone`,  `caseClassification`, `caseStatus`, `productId`, `caseManageStatus`, `initiatedBy`, `initiatedOn`, `referenceNumbers`, `primaryReporterEmail`, `productCountry`, `viewStatus`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1);]]>
</sql-query>
<sql-query id="postRejectCase">
     <![CDATA[INSERT INTO cms_cases(`registrationId`,`isCaseValid`, `reasonForRejection`) VALUES (?,?,?);]]>
</sql-query>
<sql-query id="insertAutomatedEmailData">
     <![CDATA[INSERT INTO cms_cases(`registrationId`, `reportedDate`, `routeOfEnquiryId`,
      `receievedDate`, `caseDescription`, `caseSubject`, `caseStatus`, `primaryReporterEmail`, `caseManageStatus`, `initiatedBy`, `acknowledgmentSentDate`, `version`, `isCaseValid`, `crawledCase`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?);]]>
</sql-query>
<sql-query id="insertSourcedDocumentsWithBlobData">
     <![CDATA[INSERT INTO cms_documents(`caseId`, `filename`,`fileType`,`blobFile`,`blobFileType`,`blobFileSize`) VALUES (?, ?, ?, ?, ?, ?);]]>
</sql-query>
<sql-query id="insertSourcedDocuments">
     <![CDATA[INSERT INTO cms_documents(`caseId`, `filename`,`fileType`) VALUES (?, ?, ?);]]>
</sql-query>
<sql-query id="getCaseById">
     <![CDATA[SELECT * FROM cms_cases WHERE id = ?;]]>
</sql-query>
<sql-query id="getCaseByIdXML">
     <![CDATA[SELECT c.*, cc.country_code as patientCountryCode, cr.name as routeOfEnquiryId,
          csrd.*, cc2.country_code as reporterCountry
          FROM cms_cases c 
          left outer join cms_countries cc ON c.patientCountry = cc.id
          left outer join cms_route_of_enquiry cr on cr.id = c.routeOfEnquiryId 
          left outer join cms_case_reporter_details csrd on csrd.caseId = c.id and csrd.isPrimaryReporter = 1
          left outer join cms_countries cc2 on cc2.id = csrd.reporterCountry
          WHERE c.id = ?;]]>
</sql-query>
<sql-query id="getProductsByCaseId1">
     <![CDATA[SELECT cases.productId,argus.* FROM cms_cases cases
     LEFT JOIN cms_argus_product_dictionary argus on argus.id = cases.productId
     WHERE cases.productId = ?;]]>
</sql-query>
<sql-query id="getCaseFolloupsByType">
     <![CDATA[SELECT * FROM cms_case_followups WHERE caseId = ? and followupType = ? ORDER BY followupRequestedOn;]]>
</sql-query>
<sql-query id="getAllCaseFolloupsByType">
     <![CDATA[SELECT cf.id, cf.caseId, cf.createdOn, cf.followupFile, cf.followupMessage, cf.followupRequestedBy, cf.followupType, cf.followupRequestedTo as reporterEmail, cf.followupSubject as caseSubject, cf.followupRequestedOn as reportedDate, 
               (SELECT COUNT(ccf.id) FROM cms_case_followups ccf left join cms_cases cc on ccf.caseId = cc.id WHERE (ccf.followupType = ? OR ccf.followupType = 'FORWARD_MAIL') and cc.routeOfEnquiryId = ?) as count 
               FROM cms_case_followups cf left join cms_cases c on cf.caseId = c.id WHERE (cf.followupType = ? OR cf.followupType = 'FORWARD_MAIL') and c.routeOfEnquiryId = ? ]]>
</sql-query>
<sql-query id="getAllCaseFolloupsByTypeSearchInput">
     <![CDATA[SELECT cf.id, cf.caseId, cf.createdOn, cf.followupFile, cf.followupMessage, cf.followupRequestedBy, cf.followupType, cf.followupRequestedTo as reporterEmail, cf.followupSubject as caseSubject, cf.followupRequestedOn as reportedDate, 
               (SELECT COUNT(ccf.id) FROM cms_case_followups ccf left join cms_cases cc on ccf.caseId = cc.id WHERE (ccf.followupType = ? OR ccf.followupType = 'FORWARD_MAIL') and cc.routeOfEnquiryId = ? and (ccf.followupSubject LIKE ? OR ccf.followupMessage LIKE ?)) as count 
               FROM cms_case_followups cf left join cms_cases c on cf.caseId = c.id WHERE (cf.followupType = ? OR cf.followupType = 'FORWARD_MAIL') and c.routeOfEnquiryId = ? and (cf.followupSubject LIKE ? OR cf.followupMessage LIKE ?) ]]>
</sql-query>
<sql-query id="getCaseFolloupsByCaseId">
     <![CDATA[SELECT * FROM cms_case_followups WHERE caseId = ?;]]>
</sql-query>
<sql-query id="getSourceDocsByCaseId">
     <![CDATA[SELECT * FROM cms_documents WHERE caseId = ?;]]>
</sql-query>
<sql-query id="getDocumentsDataByCaseId">
     <![CDATA[SELECT filename FROM cms_documents WHERE caseId = ?;]]>
</sql-query>
<sql-query id="getSafetyReportIdByCaseId">
     <![CDATA[SELECT * FROM cms_cases WHERE id = ?;]]>
</sql-query>
<sql-query id="getSourceDocumentsByCaseId">
     <![CDATA[SELECT cd.* FROM cms_documents cd left outer join cms_cases cc on FIND_IN_SET(cd.id, cc.caseSourceDocumentIds) where cc.id = ?;]]>
</sql-query>
<sql-query id="getMiDocumentsByCaseId">
     <![CDATA[SELECT cd.* FROM cms_documents cd left outer join cms_cases cc on FIND_IN_SET(cd.id, cc.caseMedicalDocumentsIds) where cc.id = ?;]]>
</sql-query>
<sql-query id="getDuplicateArticlesByEnquiryDetails">
     <![CDATA[SELECT * FROM cms_cases where caseSubject = ? and productId IN (?)]]>
</sql-query>
<sql-query id="getDuplicateArticlesByReporterDetails">
     <![CDATA[SELECT * FROM cms_cases where reporterEmail = ? and reporterPhone = ? and reporterCountry = ? and productId = ?]]>
</sql-query>
<sql-query id="getLastCaseId">
     <![CDATA[SELECT id FROM cms_cases ORDER BY id desc limit 1;]]>
</sql-query>
<sql-query id="updateCase">
     <![CDATA[UPDATE cms_cases SET ? where id = ?;]]>
</sql-query>
<sql-query id="updateCaseByCaseIds">
     <![CDATA[UPDATE cms_cases SET ? where FIND_IN_SET(id, ?);]]>
</sql-query>
<sql-query id="insertcaselog">
     <![CDATA[INSERT INTO cms_case_log(`caseId`,`log`,`logUserId`,`loggedBy`,`createdBy`) VALUES (?,?,?,?,?);]]>
</sql-query>
<sql-query id="insertcaseaudit">
     <![CDATA[INSERT INTO cms_case_audits(`caseId`,`userName`,`userId`,`activityType`,`fieldName`,`oldValue`,`newValue`,`stage`,`section`,`createdOn`,`createdBy`) VALUES (?,?,?,?,?,?,?,?,?,?,?);]]>
</sql-query>
<sql-query id="getCases">
     <![CDATA[SELECT * FROM cms_cases]]>
</sql-query>
<sql-query id="getCasesForInitiatorFilter">
     <![CDATA[SELECT cs.*, cr.name as routeOfEnquiryId  FROM cms_cases cs left join cms_route_of_enquiry cr on cr.id = cs.routeOfEnquiryId where cs.initiatedBy = ? and cs.caseStatus = 'Open' and cs.caseManageStatus = ? ]]>
</sql-query>
<sql-query id="getCasesForReviewerFilterAll">
     <![CDATA[SELECT cs.*, cr.name as routeOfEnquiryId  FROM cms_cases cs left join cms_route_of_enquiry cr on cr.id = cs.routeOfEnquiryId where cs.assignedTo = ? and cs.caseStatus = 'Open' and (cs.caseManageStatus = ? OR cs.caseManageStatus = 'CASEINTAKE_REJECTION') ]]>
</sql-query>
<sql-query id="getCasesForReviewerFilter">
     <![CDATA[SELECT cs.*, cr.name as routeOfEnquiryId  FROM cms_cases cs left join cms_route_of_enquiry cr on cr.id = cs.routeOfEnquiryId where cs.assignedTo = ? and cs.caseStatus = 'Open' and cs.caseManageStatus = ? ]]>
</sql-query>
<sql-query id="getCasesForApproverFilter">
     <![CDATA[SELECT cs.*, cr.name as routeOfEnquiryId  FROM cms_cases cs left join cms_route_of_enquiry cr on cr.id = cs.routeOfEnquiryId where cs.approvedBy = ? and cs.caseStatus = 'Open' and cs.caseManageStatus = ? ]]>
</sql-query>
<sql-query id="getCaseByFilter">
     <![CDATA[SELECT * from cms_cases where caseManageStatus = (SELECT ccs.sendCaseStatus from cms_role cr inner join cms_case_status ccs on cr.caseStatusId = ccs.id where cr.id = (SELECT user_role_id from cms_user where id = ?)) and caseClassification in (?)]]>
</sql-query>
<sql-query id="getCasesCount">
     <![CDATA[SELECT count(id) as count FROM cms_cases]]>
</sql-query>
<sql-query id="getCasesCountByPhone">
     <![CDATA[SELECT count(*) as count FROM cms_cases WHERE routeOfEnquiryId = 1;]]>
</sql-query>
<sql-query id="getCasesCountBySource">
     <![CDATA[SELECT cr.name,cr.id, count(c.id) as count FROM cms_cases c 
              right join cms_route_of_enquiry cr on cr.id = c.routeOfEnquiryId and c.caseManageStatus = ? and isCaseValid = true and (c.initiatedBy = ? OR c.assignedTo = ? OR c.approvedBy = ?) group by cr.name
              order by cr.id;]]>
</sql-query>
<sql-query id="getCasesCountBySourceReviewer">
     <![CDATA[SELECT cr.name,cr.id, count(c.id) as count FROM cms_cases c 
              right join cms_route_of_enquiry cr on cr.id = c.routeOfEnquiryId and (c.caseManageStatus = ? OR caseManageStatus = 'CASEINTAKE_REJECTION') and c.assignedTo = ? group by cr.name
              order by cr.id;]]>
</sql-query>
<sql-query id="getCasesCountBySourceMedicalReviewer">
     <![CDATA[SELECT cr.name,cr.id, count(c.id) as count FROM cms_cases c 
              right join cms_route_of_enquiry cr on cr.id = c.routeOfEnquiryId and caseManageStatus = ? and c.medicalReviewBy = ? group by cr.name
              order by cr.id;]]>
</sql-query>
<sql-query id="getCasesCountByClassification">
     <![CDATA[SELECT cr.name,cr.id, count(c.id) as count FROM cms_cases c 
              right join cms_case_classifications cr on FIND_IN_SET(cr.classificationStatus, c.caseClassificationStatus) and c.isCaseValid = true group by cr.name
              order by cr.id;]]>
</sql-query>
<sql-query id="getHealthAuthorityMICases">
     <![CDATA[SELECT count(*) as count FROM cms_cases_health_authority WHERE caseManagementStatus = 'Submitted For MI';]]>
</sql-query>
<sql-query id="getHealthAuthorityADRCases">
     <![CDATA[SELECT count(*) as count FROM cms_cases_health_authority WHERE caseManagementStatus = 'Submitted For ADR';]]>
</sql-query>
<sql-query id="getHealthAuthorityPQCCases">
     <![CDATA[SELECT count(*) as count FROM cms_cases_health_authority WHERE caseManagementStatus = 'Submitted For PQC';]]>
</sql-query>
<sql-query id="getCasesCountBySourceInitiator">
     <![CDATA[SELECT cr.name,cr.id, count(c.id) as count FROM cms_cases c 
              right join cms_route_of_enquiry cr on cr.id = c.routeOfEnquiryId and c.caseManageStatus = ? and isCaseValid = true and c.initiatedBy = ? group by cr.name
              order by cr.id;]]>
</sql-query>
<sql-query id="getCasesCountBySourceInitiatorEmail">
     <![CDATA[SELECT cr.name,cr.id, count(c.id) as count FROM cms_cases c 
              right join cms_route_of_enquiry cr on cr.id = c.routeOfEnquiryId and c.caseManageStatus = ? and isCaseValid = true 
              where cr.id IN(2,8) group by cr.name
              order by cr.id;]]>
</sql-query>
<sql-query id="getMICasesCountForLM">
     <![CDATA[SELECT (SELECT COUNT(*) FROM   lm_search_article where article_status = "Submitted For MI") AS pubmedCount,
                    (SELECT COUNT(*)  FROM   lm_springer_article where article_status = "Submitted For MI") AS adisinsightCount,
                    (SELECT COUNT(*)  FROM   lm_lls_articles where article_status = "Submitted For MI") AS llsCount;]]>
</sql-query>
<sql-query id="getADRCasesCountForLM">
     <![CDATA[SELECT (SELECT COUNT(*) FROM   lm_search_article where article_status = "Submitted For ADR") AS pubmedCount,
                    (SELECT COUNT(*)  FROM   lm_springer_article where article_status = "Submitted For ADR") AS adisinsightCount,
                    (SELECT COUNT(*)  FROM   lm_lls_articles where article_status = "Submitted For ADR") AS llsCount;]]>
</sql-query>
<sql-query id="getPQCCasesCountForLM">
     <![CDATA[SELECT (SELECT COUNT(*) FROM   lm_search_article where article_status = "Submitted For PQC") AS pubmedCount,
                    (SELECT COUNT(*)  FROM   lm_springer_article where article_status = "Submitted For PQC") AS adisinsightCount,
                    (SELECT COUNT(*)  FROM   lm_lls_articles where article_status = "Submitted For PQC") AS llsCount;]]>
</sql-query>
<sql-query id="getCasesByValidity">
     <![CDATA[SELECT count(*) as count, 'Rejected' as name FROM cms_cases WHERE isCaseValid = ? and caseStatus = 'Rejected' and caseManageStatus !='CASEINTAKE_REJECTION' ;]]>
</sql-query>
<sql-query id="getHealthAuthCasesByValidity">
     <![CDATA[SELECT count(*) as count, 'Rejected' as name FROM cms_cases_health_authority WHERE acceptance = ?;]]>
</sql-query>
<sql-query id="getLiteraturePubmedADRCases">
     <![CDATA[SELECT id, article_status, result_title as title, sourced_date as recievedDate, reference_number, xmlfile, argus_number from lm_search_article where article_status = ?;]]>
</sql-query>
<sql-query id="getLiteratureAdisinsightADRCases">
     <![CDATA[SELECT id, article_status, artcile_title as title, sourcedate as recievedDate, reference_number, xmlfile, argus_number from lm_springer_article where article_status = ?;]]>
</sql-query>
<sql-query id="getLiteratureLLSADRCases">
     <![CDATA[SELECT id, article_status, report_title as title, day_zero as recievedDate, reference_number, xmlfile, argus_number from lm_lls_articles where article_status = ?;]]>
</sql-query>

<sql-query id="getPUBMEDSafetyReportIdById">
     <![CDATA[SELECT id, reference_number, safetyReportId from lm_search_article WHERE reference_number = ?;]]>
</sql-query>
<sql-query id="getADISINSIGHTSafetyReportIdById">
     <![CDATA[SELECT id, reference_number, safetyReportId from lm_springer_article WHERE reference_number = ?;]]>
</sql-query>
<sql-query id="getLLSSafetyReportIdById">
     <![CDATA[SELECT id, reference_number, safetyReportId from lm_lls_articles WHERE reference_number = ?;]]>
</sql-query>

<sql-query id="updatePUBMEDArgusNumberById">
     <![CDATA[UPDATE lm_search_article SET argus_number = ? WHERE id = ?;]]>
</sql-query>
<sql-query id="updateADISINSIGHTArgusNumberById">
     <![CDATA[UPDATE lm_springer_article SET argus_number = ? WHERE id = ?;]]>
</sql-query>
<sql-query id="updateLLSArgusNumberById">
     <![CDATA[UPDATE lm_lls_articles SET argus_number = ? WHERE id = ?;]]>
</sql-query>

<sql-query id="getTotalCases">
     <![CDATA[SELECT * from cms_cases WHERE caseManageStatus = ?;]]>
</sql-query>
<sql-query id="getCaseFolloeupVersion">
     <![CDATA[SELECT substring_index (version,'-',-1) AS version from cms_cases WHERE version LIKE ?;]]>
</sql-query>
<sql-query id="getCaseExistsFromMailSubject">
     <![CDATA[SELECT id FROM cms_cases WHERE concat(' ', ? , ' ') like concat('% ', registrationId, ' %');]]>
</sql-query>
<sql-query id="getCaseExistsFromMailSubjectDesc">
     <![CDATA[SELECT id FROM cms_cases WHERE caseSubject = ? and caseDescription = ?;]]>
</sql-query>
<sql-query id="getTotalCases">
     <![CDATA[SELECT count(*) as count FROM cms_cases;]]>
</sql-query>
<sql-query id="getCaseFaqsById">
     <![CDATA[SELECT caseFaqId FROM cms_cases WHERE id = ?;]]>
</sql-query>
<sql-query id="getFaqByCaseId">
     <![CDATA[SELECT * FROM cms_cases WHERE id = ?;]]>
</sql-query>
<sql-query id="getFaqSearch">
     <![CDATA[SELECT * FROM cms_case_faq WHERE faqProductId = ? AND formulationId = ? and active = true and caseId is null;]]>
</sql-query>
<sql-query id="getFAQCountsInitiator">
     <![CDATA[SELECT
          COALESCE(sum(case when faqStatus = "FAQ_PENDING_INITIATED" and  caseId is null and active = 1 then 1 else 0 end), 0) AS pending,
          COALESCE(sum(case when faqStatus = "FAQ_INITIATED" and  caseId is null and active = 1 then 1 else 0 end), 0) AS submitted,    
          COALESCE(sum(case when faqStatus = "FAQ_APPROVED" and  caseId is null and active = 1 then 1 else 0 end), 0) AS approved
          FROM cms_case_faq ]]>
</sql-query>
<sql-query id="getFAQCountsReviewer">
     <![CDATA[SELECT
          COALESCE(sum(case when faqStatus = "FAQ_INITIATED" and  caseId is null and active = 1 then 1 else 0 end), 0) AS pending,
          COALESCE(sum(case when faqStatus = "FAQ_REVIEWED" and  caseId is null and active = 1 then 1 else 0 end), 0) AS reviewed,    
          COALESCE(sum(case when faqStatus = "FAQ_APPROVED" and  caseId is null and active = 1 then 1 else 0 end), 0) AS approved
          FROM cms_case_faq ]]>
</sql-query>
<sql-query id="getFAQCountsApprover">
     <![CDATA[SELECT
          COALESCE(sum(case when faqStatus = "FAQ_REVIEWED" and  caseId is null and active = 1 then 1 else 0 end), 0) AS pending,  
          COALESCE(sum(case when faqStatus = "FAQ_APPROVED" and  caseId is null and active = 1 then 1 else 0 end), 0) AS approved
          FROM cms_case_faq ]]>
</sql-query>
<sql-query id="addFaqToCaseById">
     <![CDATA[UPDATE cms_cases set caseFaqId = ? WHERE id = ?;]]>
</sql-query>
<sql-query id="postCaseHistory">
      <![CDATA[INSERT INTO cms_case_history(`registrationId`, `version`, `reportedDate`, `routeOfEnquiryId`, `natureOfEnquiryId`,